# Generated by Django 2.2.2 on 2019-06-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190624_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='videofile',
            field=models.FileField(default=1, upload_to='videos'),
            preserve_default=False,
        ),
    ]
