# Generated by Django 2.2.2 on 2019-06-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_movie_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
